# Generated by Django 4.2.5 on 2023-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('MT', 'Metric Ton'), ('lb', 'Pounds')], default='', max_length=2),
        ),
    ]
