# Generated by Django 4.2.5 on 2023-10-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
