# Generated by Django 4.2.5 on 2023-10-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productcategory_sam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sam',
        ),
    ]
