# Generated by Django 4.2.5 on 2023-10-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Home accessories', 'Home Accessories'), ('Stationery', 'Stationey'), ('Bags', 'Bags')], default='', max_length=20),
        ),
    ]
