# Generated by Django 4.2.5 on 2023-10-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticwaste',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plastic_waste', to=settings.AUTH_USER_MODEL),
        ),
    ]
