# Generated by Django 4.2.5 on 2023-10-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
