# Generated by Django 4.2.5 on 2023-11-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_products_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticwaste',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plastic_waste', to=settings.AUTH_USER_MODEL),
        ),
    ]
