# Generated by Django 4.2.5 on 2023-09-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='PlasticWaste',
        ),
    ]
