# Generated by Django 4.2.5 on 2023-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticwaste',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
