# Generated by Django 4.2.5 on 2023-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
